### ISSUE TITLE
Need postgres job for upgrade from v6/v7 to v8

### ISSUE THREAD

**Issue by lnguyen** [starkandwayne/shield-boshrelease#101]
Need postgres server running to do migration but job doesn't exist in release in v8. Maybe use https://github.com/cloudfoundry/postgres-release as stop gap for upgrade to v8?

**Comment by jhunt** [comment]
An alternative would be to cherry-pick the postgres / mysql stuff from a v7 bosh release into a `shield-legacy` bosh release and have people colo that.  Will test in the lab with v6/v7 → v8 migrations.

**Comment by jhunt** [comment]
Closing in favor of #120
