### ISSUE TITLE
Switch to type: ssh for shield-agent-key variable

### ISSUE THREAD

**Issue by rkoster** [starkandwayne/shield-boshrelease#109]
https://github.com/starkandwayne/shield-boshrelease/blob/master/manifests/shield.yml#L43-L44

by switching from rsa to ssh we can get the proper format for the public_key this would allow us to no longer supply private keys to the agent [(currently the public_key is calculated during startup)](https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/shield-agent/templates/bin/shield-agent#L50).

```
bosh int <(bosh int <(echo -e "foo: ((foo))\nvariables:\n- name: foo\n  type: ssh") --vars-store=/dev/null) --path /foo/public_key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG+KD6nt10/hK+byUtJyX0HPbLbXtsf0CjrWSCP+HIm/aCvFzpOyefYoivg1TIpVcAyHUx5bfVavlaVUCYaQOMIH6gmG9oModKly4wOEe572ewE0GbJyCT6L+aSo1nOI6+1jNnKchsT/WLNqwA0s+6NrJXwOyqKmz+JMCWodjKzh3eLbM6xK8KH9q3ouzfjsBqpO1fCbkE3Lptoz7iiPfjA8T//VrdMZ/gH58TerQEDD2E7aksXWFkL96IQMRIy/KHcWDFbypZufmifPtHzbu6DAMa/8hZeDOg1jRNPHqLu4r+F6saSK7cMWG9xqkTp+1ZktKg3lQiymWn7TApgzv9
```

**Comment by jhunt** [comment]
This only helps people whoa re using credhub, no?

**Comment by rkoster** [comment]
the above example only uses the bosh cli with `--vars-store`. So no credhub used. Would this conflict with genesis?

**Comment by jhunt** [comment]
I'll try to take a look at implementing this later today or tomorrow.
