### ISSUE TITLE
Unable to rotate failsafe.password for shield core

### ISSUE THREAD

**Issue by rkoster** [starkandwayne/shield-boshrelease#111]
After changing `failsafe.password` and verifying it populated into `/var/vcap/jobs/core/config/shieldd.conf`. I was unable to login with this new password.
I was able to login with `admin/shield` (the default).

**Comment by jhunt** [comment]
That is correct.

The failsafe account only gets created when there are no users in the database.

The correct way to "rotate" the password is to create a real admin account (preferably a named account) and delete the failsafe account.

**Comment by rkoster** [comment]
Thanks!
