### ISSUE TITLE
Does shield support roles instead of aws access_key and secret_key

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#117]
I have deployed bosh replacing access_key/secret_key with roles for accessing aws resources. Further I deployed shield on the bosh and tried taking bosh backup through shield, but it is failing. 
error:
No 'access_key_id' key specified in the endpoint json
No 'secret_access_key' key specified in the endpoint json

Kindly confirm if shield support roles for bosh backup

**Comment by jhunt** [comment]
It does not, currently, but PRs are welcome!
