### ISSUE TITLE
Import Errand Error(failed to connect to 10.168.10.21: Get 10.168.10.21/v2/auth/id: unsupported protocol scheme "")

### ISSUE THREAD

**Issue by cfmagnum** [starkandwayne/shield-boshrelease#119]
I am trying to take backup and restore of PostgreSQL through shield on bosh V2.
and getting error while running import errand .

failed to connect to 10.168.10.21: Get 10.168.10.21/v2/auth/id: unsupported protocol scheme ""
Below are my shield and PostgreSQL manifest file respectively

I have created shield manifest and enabled errand in PostgreSQL file.
[shield.txt](https://github.com/starkandwayne/shield-boshrelease/files/1815890/shield.txt)
[postgreSQl.txt](https://github.com/starkandwayne/shield-boshrelease/files/1815891/postgreSQl.txt)

For reference i am using this link https://github.com/starkandwayne/shield-boshrelease#the-new-import-errand

Can you please suggest ,is this the right way to configure file for taking backup through shield

**Comment by jhunt** [comment]
Set your `core` in the import configuration to include the `https://` scheme.

Here's an example: https://github.com/starkandwayne/shield/blob/master/docs/buckler.yml#L2

**Comment by lordcf** [comment]
@jhunt : Thanks for reply. Now we are able to execute the following commands:
shield api -k https://192.168.10.21:443 api
shield login --core api
After this command. We have run the import errand.
 bosh -e my-bosh run-errand import -d shield

This command its giving an error: 

Stderr     !!! <stdin>: failed to connect to http://192.168.10.21: Get https://192.168.10.21/v2/auth/id: x509: certificate signed by unknown authority

**Comment by jhunt** [comment]
If it's a self-signed cert, so you probably want to include the property to skip TLS validation:

```
insecure_skip_verify: yes
```

Otherwise, if you've got a CA, but it's not in the system trusted cert store, you can set that via:

```
ca: |
  ----- BEGIN CERTIFICATE -----
  etc.
```

**Comment by cfmagnum** [comment]
Thanks for help. now we have solve the error. Do u have any documents reference where i can reads about the configuration properties like tenenats and others and what are the changes need to be done on postgresql deployment for backup and restore?

**Comment by jhunt** [comment]
We are working on that, in tandem with getting content on the website.
