### ISSUE TITLE
shield/6.4.0 cannot be used

### ISSUE THREAD

**Issue by cppforlife** [starkandwayne/shield-boshrelease#123]
bosh.io tries to build a tarball for it, but fails with the following error:

Extracting release meta: Reading release job 'shield-agent': Building manifest: Parsing job: Expected a struct or map but was a  at line 61, column 6

**Comment by jhunt** [comment]
6.4.0 was released on November 2nd, 2016.  There have been several 6.x releases that supersede it, as well as the entire 7.x series and the 8.x betas.
