### ISSUE TITLE
Job 'nginx' not found in Template table

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#124]
Hi,
We are trying to upgrade shield from v6.8.0 to v7.0.1 , but we are getting error as below.

**Error 100: Job 'nginx' not found in Template table**

Can anyone help in this.

**Comment by jhunt** [comment]
The standalone `nginx` job was dropped in 7.0.1; the `shield-daemon` job in 7.x now contains the nginx process and is responsible for all proxying.

You may also want to give 8.0.8 a shot.

**Comment by jhunt** [comment]
for reference:

- https://github.com/starkandwayne/shield-boshrelease/blob/v7.0.1/jobs/shield-daemon/monit
- https://github.com/starkandwayne/shield-boshrelease/releases/tag/v7.0.1
- https://github.com/starkandwayne/shield-boshrelease/pull/76

**Comment by lordcf** [comment]
Hi,
We removed nginx job then i got error as below,

Error 100: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'shield'. Errors are:
    - Unable to render templates for job 'postgres'. Errors are:
      - Error filling in template 'postgres_start.sh' (line 107: no implicit conversion of String into Integer)
    - Unable to render templates for job 'shield-daemon'. Errors are:
      - Error filling in template 'ctl' (line 12: undefined method `[]' for nil:NilClass)
      - Error filling in template 'shieldd.conf' (line 10: undefined method `[]' for nil:NilClass)
      - Error filling in template 'id_rsa' (line 2: Can't find property '["ssh_private_key"]')
      - Error filling in template 'ssl_key' (line 2: Can't find property '["ssl.key"]')
      - Error filling in template 'ssl_crt' (line 2: Can't find property '["ssl.crt"]')
    - Unable to render templates for job 'shield-agent'. Errors are:
      - Error filling in template 'ctl' (line 4: You must specify either autoprovision or daemon_public_key (or both))

as we are upgrading shield on boshv1 not v2 , so do we need v2 for shield upgrade?

If yes , is there any way to migrate shield from v1 to v2.

**Comment by jhunt** [comment]
Take a look at https://github.com/starkandwayne/shield-boshrelease/blob/v7.0.1/manifests/shield.yml

Unless you're on a _really old_ version of the BOSH director, you already support "v2" stuff like job-specific properties.

**Comment by lordcf** [comment]
Hi,
We have added core.authentication property for core job, we are facing issue as follow-

 Failed: 'shield/0 ' is not running after update. Review logs for failed jobs: shieldd (00:02:26)

Error 400007: 'shield/0' is not running after update. Review logs for failed jobs: shieldd


Basically we added private key here, What will be the value we have to provide here?

We checked logs then we got shieldd logs as below-

ERROR: shield core failed to start up: failed to read agent key file /var/vcap/jobs/core/config/agent.key: ssh: no key found

**Comment by jhunt** [comment]
Yes, I believe you may be running into the same issue as the user 'Shital' in CF Slack.

The crux of the problem is that you've got an RSA key or X.509 certificate for your authentication provider configuration, which is not allowed; SHIELD can't unmarshal it as JSON, because it's not JSON.

The specific advice given in Slack was
> Your auth provider config should be a list of maps, each of which configured a different provider. That manifest has an RSA private key as the configuration, which is causing BOSH to have issues rendering the templates

It should also apply here.
