### ISSUE TITLE
How to recovery SHIELD itself?

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield-boshrelease#128]
I install SHIELD using shield-boshrelease v8.0.8.

Can I get the latest guide how to backup and recovery SHIELD itself?

**Comment by jhunt** [comment]
I don't know that we have it documented on the website yet.  I'll try to pull together a guide on https://shieldproject.io/docs and then blog about it somewhere.

**Comment by jhunt** [comment]
This is a duplicate of https://github.com/starkandwayne/shield/issues/413.
