### ISSUE TITLE
Errand 'import' completed with error (!!! <stdin>: failed to connect to : Get /v2/auth/id: unsupported protocol scheme "")

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#129]
Hi,
 I have successfully upgraded shield from v6.6.5 to v8.0.8, but now facing error while running import errand.
Errand got failed with error as shown below.

[stdout]
Connecting to
[stderr]
!!! <stdin>: failed to connect to : Get /v2/auth/id: unsupported protocol scheme ""
Errand 'import' completed with error (exit code 1)

As I have tried using  insecure_skip_verify: yes , still facing same error.
logs are as follows-
**shieldd.log**
/var/vcap/packages/shield/bin/shieldd: ERROR: Vault is currently uninitialized, please initialize or unseal the vault via the WebUI or CLI

**vault.log**
[INFO ] core: security barrier not initialized
[INFO ] core: security barrier not initialized

**Comment by jhunt** [comment]
We have added validation to the `shield import` utility to prevent this type of problem.
