### ISSUE TITLE
Unable to exec '/var/vcap/packages/mariadb/bin/mysqldump': fork/exec /var/vcap/packages/mariadb/bin/mysqldump: no such file or directory

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#133]
Hello,

For shield v8.0.8, we are facing issue while running the jobs for bakcup of CF tenants. 

Issue is:-
Unable to exec '/var/vcap/packages/mariadb/bin/mysqldump': fork/exec/var/vcap/packages/mariadb/bin/mysqldump: no such file or directory

For this issue we have tried by adding an addon into CF manifest file as follow-
name: shield-addon-mariadb-10.2
    release: shield-addon-mysql

we have uploaded release using genesis into CF manifest file.But we are facing issue at the time of CF redeloyment with this addon as follow-

troff: fatal error: can't find macro file m
**Error 450001:** Action Failed get_task: Task### result: Compiling package shield-addon-mariadb-10.2: Running packaging script: Running packaging script: Command exited with 2; Truncated stdout: -- Installing: /var/vcap/packages/shield-addon-mariadb-10.2/
include/mysql/server/mysql/service_thd_autoinc.h
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-implicit-fallthrough" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-misleading-indentation" [enabled by default]
+ make install
CMake Error at client/cmake_install.cmake:58 (FILE):
  file INSTALL cannot copy file
  "/var/vcap/data/compile/shield-addon-mariadb-10.2/mariadb-10.2.10/client/mysqltest"
  to "/var/vcap/packages/shield-addon-mariadb-10.2/bin/mysqltest".
Call Stack (most recent call first):
  cmake_install.cmake:122 (INCLUDE)

**Comment by jhunt** [comment]
Is there more to that error?

I'd wager your compilation VM ran out of disk space; I recall that being a problem in my own testing and lab setups.  The rest of the error should mention something like "No space left on device" or something similar, in that case.

**Comment by lordcf** [comment]
No, we was facing issue at compile time only.
As, Now we have increased the size of compilation vm ,  there is no issue at complie time. 
Now we are facing error as follow-

**'mysql_proxy_z1/0 ' is not running after update. Review logs for failed jobs: shield-agent**

We checked logs for shield-agent 
agent.log 

/var/vcap/jobs/shield-agent/bin/shield-agent: line 53: LD_LIBRARY_PATH: unbound variable

**Comment by lordcf** [comment]
Hi,
For this error we upgarded shield to v8.0.9 now there is no any error in cf deployment, but we are facing issue with import errand.
Import errand got failed with following error:-

**[stderr]
/var/vcap/jobs/import/bin/run: line 8: token: unbound variable
!!! <stdin>: failed to connect to : Get /v2/auth/id: unsupported protocol scheme ""**

**Comment by jhunt** [comment]
Yes, you are looking for the fix in 5e3cc10, via #132.  Try 8.0.12, which includes that fix.

**Comment by jhunt** [comment]
Any luck?
