### ISSUE TITLE
failed to connect to : Get /v2/auth/id: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#136]
Hello,
We are deploying fresh deployment of V8.0.8 shield-bosh-release on our bosh2 env.
Deployment succeeded for v8.0.8, but import errand failed with following errror.

_**Exit Code  1
Stdout     Connecting to

Stderr     !!! <stdin>: failed to connect to : Get /v2/auth/id: unsupported protocol scheme ""

1 errand(s)

Errand 'import' completed with error (exit code 1)

Exit code 1**_
 

Here proving our manifest file.

[shield.txt](https://github.com/starkandwayne/shield-boshrelease/files/2205420/shield.txt)

**Comment by jhunt** [comment]
I believe your `core` property under the import errand is missing the `https://` scheme.

I also notice you are running 8.0.8; import got some validation fixes in 8.0.11 <https://github.com/starkandwayne/shield/releases/tag/v8.0.11>, which you may want to update to (or, at your discretion, 8.0.13, released last Friday).

https://github.com/starkandwayne/shield/releases/latest

**Comment by jhunt** [comment]
This sounds like the same issue the @lordcf user was having in https://github.com/starkandwayne/shield-boshrelease/issues/129

**Comment by lordcf** [comment]
We have provided core property under the import errand as follow
 jobs:
      - name: import
        properties:
          import:
            core: https://IP:443


Now we tried with v8.0.11 having issue with core only as follow-

Exit Code  1
Stdout     importing now......

Stderr     !!! <stdin>: Missing requird 'core' top-level key in the import manifest.

**Comment by jhunt** [comment]
can you verify the indent level in your manifest?  here on github, it looks like nothing is properly indented...

**Comment by lordcf** [comment]
Hi 

I checked manifest, as indentation is proper for import job , please have a look on below shield.txt file

[shield.txt](https://github.com/starkandwayne/shield-boshrelease/files/2208729/shield.txt)

**Comment by jhunt** [comment]
Can you also post `/var/vcap/jobs/import/config/import.yml`?

**Comment by lordcf** [comment]
I checked this import.yml file , it is blank .

import.yml
--- {}

**Comment by lordcf** [comment]
Hi,
This issue resolved , there was indentation issue only.
Now able to run import errand, test-store task also done, but now facing issue with backup , backup task is in failed status.

Error is as follow-
 **mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")"
when trying to connect
            Unable to exec '/var/vcap/packages/mariadb/bin/mysqldump': exit status 2

            EXITING 3
            shield worker 4 unable to run command against   ##IP##**
