### ISSUE TITLE
Getting Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock'

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#139]
Hi,

We have deployed shield v8.0.11 .
Able to run import errand, test-store task also done, but now facing issue with backup , backup task is in failed status.

Error is as follow-
**mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")"
when trying to connect
Unable to exec '/var/vcap/packages/mariadb/bin/mysqldump': exit status 2

        EXITING 3
        shield worker 4 unable to run command against   ##IP##**

**Comment by jhunt** [comment]
Sounds like you are using default socket paths, which won't work in a BOSH environment.

You probably want to check the `mysql_options` field for the `mysql` plugin:

http://shieldproject.io/docs/plugins/#mysql-mariadb

**Comment by lordcf** [comment]
Hi,
We have successfully resolve the issue. The backup stores without prefix. is there any configuration where i can provides the prefix of all databases?
