### ISSUE TITLE
Support for Azure-Stack Blobstore

### ISSUE THREAD

**Issue by lordcf** [starkandwayne/shield-boshrelease#143]
Currently shield supports azure public cloud blob storage, however azure stack blobstore access fails with below error. We tried using the AzureStack Storage account with valid access keys.
Performing store / retrieve / purge test
            ========================================
            generating an input bit pattern
            storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

However, when we switched our storage account to utilize Azure Public cloud, we could access the blobstore.

Do we have different configuration to support azure stack blobstore for shield?

This was tried with using ver 8.0.8

**Comment by lordcf** [comment]
We also tried to utilize the latest shield released version 8.0.16 for the Stack Blobstore, however we saw the same error as above.

**Comment by jhunt** [comment]
We do not currently support AzureStack, although we would welcome a PR to add support into the existing `azure` plugin, or via a new plugin.  Please join us in Slack to discuss!
