### ISSUE TITLE
Route registrar bosh release and shield v8 bosh release

### ISSUE THREAD

**Issue by JCL38-ORANGE** [starkandwayne/shield-boshrelease#146]
Hello,

We are using route registrar bosh release (https://bosh.io/releases/github.com/cloudfoundry-community/route-registrar-boshrelease?version=3) in front of shield web ui.
This works perfectly with V6.
With Shield V8, it doesn't work out of the box. In order to make it working, I need to update the file shieldd.conf (change parameter listen_addr from value 127.0.0.1:8080 to value 0.0.0.0:8080).
What do you think about that ?
Thanks and regards,
Jean-Christophe.

**Comment by jhunt** [comment]
see https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/core/templates/config/nginx.conf#L86

**Comment by JCL38-ORANGE** [comment]
Hello James,

Thanks for your quick answer.
So I need to configure route registrar with 80 as target port ?  
I tried but it fails on my own.
Did I misunderstand ?
Today I am at the CF Summit at Basle. Maybe we can meet to discuss on that ?
Thanks and regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

Thanks a lot. It works as expected.
Regards,
Jean-Christophe.
