### ISSUE TITLE
Configuration of a simple backup job (backup fs with shield agent) in shield V8

### ISSUE THREAD

**Issue by JCL38-ORANGE** [starkandwayne/shield-boshrelease#147]
Hello,

I have configured a simple backup job in shield V8 (backup fs /var/vcap/store/shield).
I am facing with the following error in the full task log :+1: 
...
Running backup task (using bzip2 compression)
=============================================
 (InvalidDateFieldInRequest) [raw 
InvalidDateFieldInRequest
]

EXITING 4
shield worker 1 unable to run command against 127.0.0.1:5444
...

I followed your getting started guide in order to configure a such backup.
Thanks for your help and regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

Could I have support on that ?
Thanks in advance,
Jean-Christophe.

**Comment by jhunt** [comment]
I have no idea who or what is giving back the `InvalidDateFieldInRequest`.  Is it possible this is a lower-level HTTP thing, possibly related to an intervening proxy?

**Comment by JCL38-ORANGE** [comment]
Hello,

I re-open this issue.
I am targeting the following S3 storage +> https://www.orange-business.com/fr/produits/flexible-storage
When I target a S3 storage (auth v2) with the S3 plugin, the following error is raised :   
...
(InvalidDateFieldInRequest) [raw
InvalidDateFieldInRequest
]

EXITING 4
shield worker 1 unable to run command against 127.0.0.1:5444
...
Previously, we used the scality plugin with this S3 storage. It was working perfectly.
Currently, it works well with an another S3 storage (auth V4) like minio bosh release or AWS.
Is the problem related to https://github.com/starkandwayne/shield/issues/464 ?
Thanks in advance for your help.
Regards,
Jean-Christophe.

**Comment by jhunt** [comment]
Please don't spam the issue tracker.

**Comment by JCL38-ORANGE** [comment]
James,

There was an issue with GitHub this morning (data recovery).
I close this ticket.
Regards,
Jean-Christophe.
