### ISSUE TITLE
database as a backend for vault

### ISSUE THREAD

**Issue by nbari** [starkandwayne/shield-boshrelease#149]
If a backup of the vault is required, currently the vault needs to be stopped, (do the backup) and then start it again, having a database as a backend prevents the stop-start procedure .

This is a PR https://github.com/starkandwayne/shield-boshrelease/pull/148 that if defined with the following params it will use MySQL as a backend:

    backend:
       mysql_address:  "x.x.x.x:3306"
       mysql_username: "user" 
       mysql_password: "pass"
       mysql_database: "vault"

**Comment by jhunt** [comment]
I appreciate the time and effort that went into this PR, but would prefer not to merge it.  Feel free to join us in Slack and discuss the desire for non-local Vault backends in an appliance solution.
