### ISSUE TITLE
Make autoprovisioning better

### ISSUE THREAD

**Issue by lnguyen** [starkandwayne/shield-boshrelease#15]

**Comment by geofffranks** [comment]
1. Add a cron task to repeatedly poll the autoprovision URL to retrieve a key, if one does not already exist
2. Ensure that we have the ability to specify host private + public keys for the agents, via the BOSH manifest, or that `shield-daemon` ignores host keys changing, to allow happier SSH-ing across stemcell upgrades
3. Ensure we have the ability to specify a private + public ssh key for `shield-daemon` to connect to `shield-agents` with, via the BOSH manifest

**Comment by jhunt** [comment]
Minus the cron task, this is almost all done now.  Yay!

**Comment by jhunt** [comment]
For future me: the reason for the cron job is to handle key changes on the daemon side, without having to explicitly bump the agent deployments.

**Comment by jhunt** [comment]
v8 moves the autoprovisioning task to be an idempotent errand that can be scheduled however operators see fit.
