### ISSUE TITLE
Plugin S3 fails with a storage using auth v2

### ISSUE THREAD

**Issue by JCL38-ORANGE** [starkandwayne/shield-boshrelease#150]
Hello,

I am targeting the following S3 storage => https://www.orange-business.com/fr/produits/flexible-storage
When I target a S3 storage (auth v2) with the S3 plugin, the following error is raised :   
...
(InvalidDateFieldInRequest) [raw
InvalidDateFieldInRequest
]

EXITING 4
shield worker 1 unable to run command against 127.0.0.1:5444
...
Previously, we used the scality plugin with this S3 storage. It was working perfectly.
Currently, it works well with an another S3 storage (auth V4) like minio bosh release or AWS.
Is the problem related to https://github.com/starkandwayne/shield/issues/464 ?
Thanks in advance for your help.
Regards,
Jean-Christophe.

**Comment by jhunt** [comment]
Please don't spam the issue tracker.

**Comment by JCL38-ORANGE** [comment]
Hello James,

Sorry there was an issue with Github this morning (data recovery).
I close this ticket.
Regards,
Jean-Christophe.
