### ISSUE TITLE
what we miss "edit systems in the web-ui"

### ISSUE THREAD

**Issue by Klojo** [starkandwayne/shield-boshrelease#159]
Hello,

some times we must change some passwords.. Or some systems get a new ip-adress etc.
but there is no link to edit or delete the system, which is at storage, there is a delete and edit option.

it is beter for some operators/engineers, that they can change it in the web gui.

best regards

**Comment by jhunt** [comment]
This is in v8.1.0! (https://github.com/starkandwayne/shield-boshrelease/releases/tag/v8.1.0)
