### ISSUE TITLE
Bosh.io has no recent releases, 6.4.0 was a bad release

### ISSUE THREAD

**Issue by mrosecrance** [starkandwayne/shield-boshrelease#162]
The pipeline to ingest this release for display on bosh-io hasn't run successfully since `v7.0.2`.

Specifically it looks like `6.4.0` was an invalid release and at the moment, the pipeline does not search any further once an error occurs.

```
panic: Failed: Processing release: release=misc.Release{DirPath:"/tmp/build/6b387ced/release", MFPath:"/tmp/build/6b387ced/release/releases/shield/shield-6.4.0.yml", releaseReaderFactory:release.ReaderFactory{downloader:downloader.MuxDownloader{mux:map[string]downloader.Downloader{"file":downloader.LocalFSDownloader{fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}}, logger:(*logger.logger)(0xc00000de40), downloadedPaths:map[string]downloader.Downloader{}}, extractor:tar.CmdExtractor{runner:system.execCmdRunner{logger:(*logger.logger)(0xc00000de40)}, fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}, fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}, jobReaderFactory:job.ReaderFactory{downloader:downloader.MuxDownloader{mux:map[string]downloader.Downloader{"file":downloader.LocalFSDownloader{fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}}, logger:(*logger.logger)(0xc00000de40), downloadedPaths:map[string]downloader.Downloader{}}, extractor:tar.CmdExtractor{runner:system.execCmdRunner{logger:(*logger.logger)(0xc00000de40)}, fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}, fs:(*system.osFileSystem)(0xc000076e40), logger:(*logger.logger)(0xc00000de40)}} Extracting release meta: Reading release job 'shield-agent': Building manifest: Parsing job: Expected a struct or map but was a  at line 61, column 6 
```
If you don't care to fix this release but want to update bosh-io, you can remove the file from https://github.com/starkandwayne/shield-boshrelease/tree/master/releases/shield 

If you don't care about having this on bosh-io, that would also be good to know.

**Comment by jhunt** [comment]
I'm curious what was wrong with 6.4.0 (https://github.com/starkandwayne/shield-boshrelease/releases/tag/v6.4.0)?

**Comment by mrosecrance** [comment]
The bosh-io pipeline builds the release from scratch and then we host it ourselves. There's probably some historical context on why we don't just pull from github premade releases but I think doing that refactor isn't a high priority at the moment. 

We've gone ahead and bumped the min version to display on bosh-io to 6.4.1 and all the releases since then have been consumed successfully, so I'll close this issue.

**Comment by jhunt** [comment]
Thanks, and apologies for the inconvenience!
