### ISSUE TITLE
Cloud storage are marked as failing when I migrate from 8.0.17 to 8.1.0

### ISSUE THREAD

**Issue by JCL38-ORANGE** [starkandwayne/shield-boshrelease#165]
Hello,

Cloud storage are marked as failing when I migrate from 8.0.17 Bosh-Release to 8.1.0 Bosh-Release.
Cloud storage definitions are configured in the errand import which loads the configuration as follow : 
...
- name: minio
            summary: |
              Minio cloud storage for all SHIELD tenants to use
            agent:  127.0.0.1:5444
            plugin: s3
            config:
              s3_host: ((minio_s3_host))
              s3_port: "443"
              access_key_id: ((minio_s3_access_key_id))
              secret_access_key: ((minio_s3_secret_access_key))
              signature_version: "4"
              bucket: ((s3_bucket_prefix))-bucket #pre-requisite
              skip_ssl_validation: true
...
The same configuration works properly with 8.0.17 release and not with 8.1.0.
Thanks in advance for your help,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

I found the problem.
The minio_s3_host must now include the protocol.
Prior 8.1.0 the s3_host value is : <my_host> 
With 8.1.0 the s3_host value must be : <https://my_host>
Regards,
Jean-Christophe.

**Comment by jhunt** [comment]
Interesting.  I'll put in a feature request to auto-munge that where necessary.
