### ISSUE TITLE
When deploying via bosh-init ip address of target configuration not set.

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield-boshrelease#43]
We deployed a bosh with bosh-init and included the shield agent with target and job sections configured. When registering with the shield daemon the 'Remote IP:Port' was configured as `:5444`. It looks like [this line](https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/shield-agent/templates/bin/post-start.erb#L27) where the ip is being determined isn't interpreted with bosh-init the same way as with regular bosh.

**Comment by jhunt** [comment]
Should we just make ip a settable manifest property and bail in the template if it's not set _and_ not discoverable?

**Comment by bodymindarts** [comment]
Sounds good
