### ISSUE TITLE
v6.4.0: syntax error in shield-agent ctl script

### ISSUE THREAD

**Issue by bgandon** [starkandwayne/shield-boshrelease#49]
On the `shield/0` VM, the `/var/vcap/jobs/shield-agent/bin/ctl` startup script has an issue producing this error:

```
# tail  /var/vcap/data/sys/log/monit/shield-agent.log
/var/vcap/jobs/shield-agent/bin/ctl: line 22: syntax error near unexpected token `}'
```

This is due to both `if_p("shield.agent.autoprovision")` and `if_p("shield.agent.daemon_public_key")` evaluating to `false` and not rendering their respective blocks. Even when these are set in the deployment properties, which is strange. Anyway, this issue could easily be circumvented with a mere call to `/bin/true` within the curly braces so that the block is never empty from a Bash syntax point of view.

(This issue was originally part of issue #48.)

**Comment by jhunt** [comment]
As I said in #48, just papering over the issue with a `/bin/true` would be problematic.  Essentially, that's blessing configurations of the SHIELD agent where there are no authorized keys.  Without authorized keys, no SHIELD core is going to be able to instrument the agent, since the agent only accepts connections from authorized cores.

Instead, we should probably `raise` an error so that the problem is caught in template rendering / deployment prep, prior to actually spinning up VMs and placing configuration on them.

**Comment by bgandon** [comment]
@jhunt said:
> Interesting. In no case should `shield.agent.autoprovision` AND `shield.agent.daemon_public_key` be omitted. Perhaps we should `raise` an error if we don't get either of them, rather than generate a configuration of an agent that literally cannot be used.

Ok I found the problem, which might be a flaw in the version of BOSH director I'm using (v1.3215.3.0 a.k.a. v255.8, released 2016-04-02).

I just had customized the agent log level at job-level properties:

```yaml
    - name: shield-agent
      release: shield
      properties:
        shield:
          log_level: info
```

And it turns out that commenting out this property customization solved the problem and leaded to the `bin/ctl` template properly being rendered. Maybe it's a known issue of old BOSH versions, maybe not. Anyway, it doesn't seem SHIELD-related.

Yes, indeed, we should raise an error in case of misconfiguration regarding `shield.agent.autoprovision` and `shield.agent.daemon_public_key`. Also update the properties description in job's spec to specify that at least one of those two needs to be provided.

**Comment by jhunt** [comment]
My understanding of "job"-level properties is that you lose visibility to the global and instance-level properties.  I believe this is by design; the solution being to not use job-level props, and either use top-level or instance-level instead.

**Comment by bgandon** [comment]
OK indeed, I see my misunderstanding now. I had written job properties instead of instance properties, not being aware of the difference. Thanks for pointing this out.
