### ISSUE TITLE
shield.daemon.domain not used in shield-agent

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield-boshrelease#51]
I cannot find where [these properties](https://github.com/starkandwayne/shield-boshrelease/blob/c2e49432ee0fac7c759153600984d8dac5035c7f/jobs/shield-agent/spec#L54-L58) are being referenced.
It look like the logic on the [post-start script](https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/shield-agent/templates/bin/post-start#L17) has changed to expect the `shield.agent.autoprovision` property to be the server endpoint.

**Comment by jhunt** [comment]
Can you remove the property from the spec file and then test it locally to ensure that it doesn't cause any regressions?

**Comment by bodymindarts** [comment]
yup will do

**Comment by jhunt** [comment]
They are used here: https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/shield-daemon/templates/config/shieldd.conf#L30
