### ISSUE TITLE
Floating IP doesn't redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by quintessence** [starkandwayne/shield-boshrelease#54]
When using a floating IP in Openstack, HTTP does not redirect to HTTPS it hangs, attempts to redirect to the internal IP, and then fails. 

e.g. `http://172.x.x.114` -> `http://10.4.1.32` not `https://172.x.x.114`

**Comment by gogolok** [comment]
https://github.com/starkandwayne/shield-boshrelease/blob/master/jobs/nginx/templates/config/nginx.conf#L48

return 301 https://$host$request_uri;
