### ISSUE TITLE
Support Bosh Link to allow a multi VM deployment

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield-boshrelease#56]
Hey

This is a `feature-request`.

It would be great if the `shield-boshdeployment` would support [`bosh` links](https://bosh.io/docs/links.html) which would allow to install `nginx` and `shield` in a dedicated vm and stuff like `shield.daemon.database.host` would not have to be set statically.

(I hope to find some time to implement this on my own.)

cheers

**Comment by jhunt** [comment]
@janaurka have you found the time to implement this on your own, or should we take a crack at it?

**Comment by janaurka** [comment]
@jhunt: unfortunately i did not fine any time to get this implemented :( 

if you have some time, sure.

**Comment by jhunt** [comment]
I looked at this again this morning; the way we have set up the authentication and whatnot for postgres (`databases.roles.[tag=...]`) doesn't work very well with links.

I'm proposing we add a new `database` job that can self-select postgres / mysql, and can be linked appropriately using bosh v2 semantics.  The link would be optional, at least until we decide people have had enough time to migrate.

Thoughts?

**Comment by xanderrman** [comment]
@janaurka just checking in to see if this is still helpful; Thanks 👍

**Comment by jhunt** [comment]
As we roll out v7, more and more of SHIELD is moving into a single VM anyway, so I'm not sure we still need links...

**Comment by janaurka** [comment]
Sorry, running around on the summit, did not find the time to reply here. I guess it’s not required anymore, so I’ll close this.
