### ISSUE TITLE
Add xtrabackup as package/job

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield-boshrelease#59]
Hey

This is a feature request.

Can you add `xtrabackup` as package/job (probably best as new job)? There was a plugin added to `shield` and it would be awesome if this could be used with this boshrelease out of the box.

(I’d do this on my own but I currently don’t understand where the code needs to be. According to the `bosh` documentation I’d expect something like a `blob` directory, where the `xtrabackup` code/application lives but there is none)

cheers

**Comment by gogolok** [comment]
https://github.com/starkandwayne/shield-boshrelease/pull/55 is ready to be reviewed.

**Comment by gogolok** [comment]
@jhunt can be closed since #55 has been merged.

**Comment by jhunt** [comment]
I don't want to be closed.  But I'll happily close this issue!
