### ISSUE TITLE
Update to golang 1.5.2

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/shield-boshrelease#6]

**Comment by filefrog** [comment]
Can we update to 1.5.3, given the math/big CVE (https://groups.google.com/forum/#!topic/golang-nuts/MEATuOi_ei4)?

**Comment by longnguyen11288** [comment]
fixed in https://github.com/starkandwayne/shield-boshrelease/commit/d8d7cf1327ec755c00ebc53b66e843b4d853ba64
