### ISSUE TITLE
task fail, run job (ssh: handshake failed: EOF)

### ISSUE THREAD

**Issue by shik0912** [starkandwayne/shield-boshrelease#60]
Hello, I'v been testing shiled on my local bosh-lite.

command : shield run [jobs name] -k
result :
![1234](https://cloud.githubusercontent.com/assets/20904386/22192712/9ed023ca-e179-11e6-9721-13eb496a1e59.png)

shieldd log :
2017-01-23 04:07:35.545134238 +0000 UTC shieldd: INFO: schedule adhoc backup job
2017-01-23 04:07:35.545204147 +0000 UTC shieldd: INFO: scheduling immediate (ad hoc) execution of job shield [625738c4-db29-46fc-8fd7-af5ee6d11e15]
2017-01-23 04:07:35.547435938 +0000 UTC shieldd: INFO: schedule task dab38689-15f2-40aa-861a-9f1c256316db with deadline {{63620784455 547401390 0x1157da0}}
2017/01/23 04:07:35 http: multiple response.WriteHeader calls
2017-01-23 04:07:35.966399278 +0000 UTC shieldd: INFO: sent a task to a worker
2017-01-23 04:07:35.966703638 +0000 UTC shieldd: INFO:   dab38689-15f2-40aa-861a-9f1c256316db> TASK FAILED!!  shield worker 5 unable to connect to 10.244.204.2:443 (ssh: handshake failed: ssh: invalid packet length, packet too large)
2017-01-23 04:07:35.975731706 +0000 UTC shieldd: WARNING:   dab38689-15f2-40aa-861a-9f1c256316db: task failed!
2017-01-23 05:30:40.733353999 +0000 UTC shieldd: INFO: schedule adhoc backup job
2017-01-23 05:30:40.73347915 +0000 UTC shieldd: INFO: scheduling immediate (ad hoc) execution of job shield [625738c4-db29-46fc-8fd7-af5ee6d11e15]
2017-01-23 05:30:40.735746302 +0000 UTC shieldd: INFO: schedule task 52110f7e-636f-43e8-9a97-4d876cab765a with deadline {{63620789440 735728122 0x1157da0}}
2017/01/23 05:30:40 http: multiple response.WriteHeader calls
2017-01-23 05:30:40.963795183 +0000 UTC shieldd: INFO: sent a task to a worker

my bosh vms, below
+-------------------------------------------------+---------+-----+----------+--------------+
| VM                                              | State   | AZ  | VM Type  | IPs          |
+-------------------------------------------------+---------+-----+----------+--------------+
| shield/0  | running | n/a | small_z1 | 10.244.204.2 |
+-------------------------------------------------+---------+-----+----------+--------------+
+---------------------------------------------------------------+---------+-----+----------+-------------+
| VM                                                            | State   | AZ  | VM Type  | IPs         |
+---------------------------------------------------------------+---------+-----+----------+-------------+
| postgresql_docker_z1/0  | running | n/a | small_z1 | 10.244.30.6 |
+---------------------------------------------------------------+---------+-----+----------+-------------+
+---------------------------------------------------------------+---------+-----+----------+-------------+
| VM                                                            | State   | AZ  | VM Type  | IPs         |
+---------------------------------------------------------------+---------+-----+----------+-------------+
| postgresql_docker_z1/0 | running | n/a | small_z1 | 10.244.40.6 |
+---------------------------------------------------------------+---------+-----+----------+-------------+

my job
Name:             shield
Paused:           N
Retention Policy: default
Expires in:       100 days
Schedule Policy:  default
Target:           postgres
Target Endpoint:  {"pg_user":"target", "pg_password":"target", "pg_host":"10.244.40.6", "pg_port":"5432"}
Remote IP:        10.244.204.2:5524
Store:            postgres
Store Endpoint:   {"pg_user": "store", "pg_password": "store", "pg_host": "10.244.30.6", "pg_port": "5432"}
Notes:            shield

IP & Port of  Target & Store is correct. I saw init.script of test-bed.
I've thought that i don't understand shield.

I wait your reply.

**Comment by shik0912** [comment]
After modified .yml file about agent, I deployed psql of target, store.
I checked 'running'.

**Comment by jhunt** [comment]
I see two problems:

First, your `Remote IP` should be the IP address and port of the SHIELD agent that will actually do the postgres backup (i.e. run the `pg` plugin).  Normally, that agent runs on 5444 (unless you changed `shield.agent.port` in your deployment manifest).

IIRC, port 5524 is what several Cloud Foundry / BOSH components use for their internal postgres components, which would explain the "handshake failed: EOF" -- SHIELD is connecting to something, trying to talk SHIELD agent protocol, and that something (a Postgres database) is closing the connection because it doesn't understand.

What happens if you change `Remote IP` in your target configuration to `127.0.0.1:5444`?

Secondly, you've got your _store_ set to a Postgres endpoint as well.  _Store_ is where SHIELD should store the backup archive files.  This is usually something like `s3`, or `fs`.  Per the documentation for the `pg` plugin (https://godoc.org/github.com/starkandwayne/shield/plugin/postgres) store operations are not supported.

You will want to configure a store plugin.  I'd recommend `fs` (https://godoc.org/github.com/starkandwayne/shield/plugin/fs)

**Comment by shik0912** [comment]
I appreciate your reply.
I did your first resolution that apply 127.0.0.1:5444
below is result about that.
![127 0 0 1 5444](https://cloud.githubusercontent.com/assets/20904386/22228523/18097ebc-e215-11e6-83dc-284cdf193c27.png)

After apply second resolution, i will comment result !

**Comment by shik0912** [comment]
I applied second resolution, But it has a matter.

below is result.
![Uploading after modify fsStore.png…]()

I think that remote port is not correct. below is target-psql.yml about agent.
I didn't modify port.
![target-docker agent yml](https://cloud.githubusercontent.com/assets/20904386/22234579/7df0cb6e-e23c-11e6-8ff2-5193519ebe9c.png)

JOB for fs store summary.
![show job after modifying fsstore](https://cloud.githubusercontent.com/assets/20904386/22234594/aa5d04ce-e23c-11e6-8fc6-eaedca9a3eb5.png)

STORE for configuration fof fs store.
Name:          store-fs
Summary:       store-fs               
Plugin:        fs
Configuration: {"base_dir": "~/Research/shield-store"}

base_dir is my local direcotry.

Summary,
first, /var/vcap/packages/postgres/bin/pg_dumpall...
i checked at packages of VM. it is on the spot. 
so, i tested executing the file on the spot. result is same log...

second, remote agent IP:PORT
it is very confused.... 

i wait your reply !

**Comment by shik0912** [comment]
I see with-example-inputs.yml in bosh-release.
...
properties:
 targets:
  plugin: fs
...
I saw it, so I will apply it target properties of my yml...

**Comment by jhunt** [comment]
Are you putting the `agent-pgtools` job/template on the SHIELD agent deployment?

**Comment by shik0912** [comment]
thx jhunt, It worked it !
![shield backup result](https://cloud.githubusercontent.com/assets/20904386/22272997/2c78932a-e2e1-11e6-8520-9bb4e58bb6aa.png)

I added on my shield deployment yml file
![shield backup result](https://cloud.githubusercontent.com/assets/20904386/22273045/79ab060a-e2e1-11e6-8bfd-cad998d71b53.png)

Thanks for your kindness have a good day !

**Comment by jhunt** [comment]
Happy to help!
