### ISSUE TITLE
cf backup & restore 

### ISSUE THREAD

**Issue by shik0912** [starkandwayne/shield-boshrelease#66]
Hello! I've been using shield on bosh.
I finished about simple test that backup & restore of postgresql-docker.
So, I've tested backup & restore of cloud foundry.

Below is my plan
first, CCDB
second, UAA
...
Applcation of blobstore
...

Well.. I'm blocked by restore of CCDB. I did only backup, 
But, It is not definitely. bcuz restore is not working.

my scenario is very simple.
1. I have a space on cf.
2. backup it.
3. delete the space.
4. restore it.
5. check the space on CCDB.
but, it is not working about restore.

task log is very long. So, I attached txt file.
It is return exiting 0.
[cf restore log (it is not working).txt](https://github.com/starkandwayne/shield-boshrelease/files/753974/cf.restore.log.it.is.not.working.txt)

Below is my settings.

1. Job on shield for Cloud Foundry
![cf restore job](https://cloud.githubusercontent.com/assets/20904386/22639116/b6770df6-ec8f-11e6-9da0-5e43ffdd5ed6.png)

2. bosh vms
![bosh vms](https://cloud.githubusercontent.com/assets/20904386/22639139/dec2b8a0-ec8f-11e6-9d90-d365ef15025e.png)

3. cf yml file (cloud foundry version is v238) 
- github doesn't support .yml, so i changed .txt

I set setting that is same success of postgresql docker.

I wait your reply :D

**Comment by jhunt** [comment]
What is in the `spaces` table on the ccdb, (a) before the backup, (b) before the restore and (c) after the restore?

Also, can you share the output of `cf spaces` at all three points in time?

**Comment by shik0912** [comment]
Hi, i captured your request.

(a)
![cf before backup](https://cloud.githubusercontent.com/assets/20904386/22672302/4c3540fc-ed16-11e6-9b7c-5168a1ac63c1.png)

(b) 
![cf before restore](https://cloud.githubusercontent.com/assets/20904386/22672313/5fdb23ec-ed16-11e6-8efa-808113957642.png)

(... restore job)
![cf restore job](https://cloud.githubusercontent.com/assets/20904386/22672326/740ddd00-ed16-11e6-8f81-7199a10b81b2.png)

(c) 
![cf after restore](https://cloud.githubusercontent.com/assets/20904386/22672317/66d3756e-ed16-11e6-8761-78814a763451.png)

shield show task is same, cf restore log (it is not working).txt

**Comment by jhunt** [comment]
Can you verify that the `space` space is present in the backup archive?  Backup archive data is bzip-compressed, so you will need to run the archive files from S3 through `bunzip2` to read them.  `postgres`-plugin backups are just SQL commands, IIRC.

**Comment by shik0912** [comment]
When I used store-FS, I checked Backup archive on base_dir.
It is on the spot.

**Comment by jhunt** [comment]
Is this in a BOSH-lite?

**Comment by shik0912** [comment]
yes BOSH-LITE on my local

**Comment by jhunt** [comment]
Can you attach the BOSH manifest you used to deploy cf?  I'd like to reproduce this in my lab.

**Comment by shik0912** [comment]
I've used bosh-lite through vagrant VM on my local.
I'm guided by bosh.io

below is stemcell version for bosh-lite.
bosh-stemcell-3312.7-warden-boshlite-ubuntu-trusty-go_agent.tgz

I attach yml file of shield and cf, that is used to test it.
[cf_v238-shield.txt](https://github.com/starkandwayne/shield-boshrelease/files/759400/cf_v238-shield.txt)
[shield-warden-manifest.txt](https://github.com/starkandwayne/shield-boshrelease/files/759401/shield-warden-manifest.txt)

github doesn't support .yml, so I changed .txt

**Comment by jhunt** [comment]
Just wanted to drop a line to let you know I haven't forgotten about this issue; I've just been stuck on other stuff.  Hopefully, I'll get my lab environment spun back up this weekend.
