### ISSUE TITLE
Rename the xtrabackup package to avoid conflicts

### ISSUE THREAD

**Issue by bgandon** [starkandwayne/shield-boshrelease#70]
The `xtrabackup` binary version `2.2.10` shipped by the cf-mysql release `v26` doesn't support the `--move-back` option on which the xtrabackup SHIELD plugin relies.

In such situation, the `xtrabackup` job of the shield-boshrelease is supposed to help. Unfortunately, it brings an `xtrabackup` package whose name conflicts with the one already installed by the `mysql` job of the cf-mysql release.

A solution for the SHIELD release would be to rename the `xtrabackup` package into `xtrabackup-2.4.5` so that it doesn't conflict with the default `xtrabackup` package shipped by the `mysql` job of the cf-mysql release.

**Comment by drnic** [comment]
@bgandon will #86 do the trick?

**Comment by bgandon** [comment]
Yes indeed, thanks!
