### ISSUE TITLE
Backup compression algorithm

### ISSUE THREAD

**Issue by szaouam** [starkandwayne/shield-boshrelease#72]
Hello,

I am using the shield-boshrelease to backup the Cloud Foundry blobstore.

The release are using bzip2 to compress backups so it may take a long time (for huge amount of data).

My question is : what about to have a new feature that enable to change the compress algorithm (user can choose between tar,bzip2,..), so for example having it as a parameter in the bosh-release manifest.

Best regards,

**Comment by jhunt** [comment]
I'd be curious to see the benchmarks on bzip2 taking "a long time" for various archive sizes

**Comment by szaouam** [comment]
Hello,

I used the fs plugin to backup up the Cloud Foundry blobstore.

I backuped the /var/vcap/store/shared folder. 

The size of the backuped folder is 105 GB.

Shield took 7h to perform the backup.

![capture](https://cloud.githubusercontent.com/assets/22029437/25737358/977f78a2-3177-11e7-9460-0a7523050f83.JPG)

The final size of the backup is 101,1 GB. 

![capture2](https://cloud.githubusercontent.com/assets/22029437/25737538/b6500066-3178-11e7-80a8-3de76b4776af.JPG)

Best regards

**Comment by geofffranks** [comment]
Where was the store for the backup pointed? Could the slowness be related to network upload speed?

**Comment by szaouam** [comment]
@geofffranks 
I am using an internal s3 storage service. 
I uploaded the same amount of data using an s3 client. It took about 1 hour.

**Comment by jhunt** [comment]
Which S3 client?

**Comment by jhunt** [comment]
Also, what is backing your s3 storage API? (assuming it's not on-prem AWS 😉)

**Comment by szaouam** [comment]
@jhunt , i used s3cmd .

Right i am not using on-prem AWS  :) .

**Comment by jhunt** [comment]
Just to double-check, when you uploaded the _same amount of data_, were you standing on the same VM that was executing the s3 plugin in the slow-scenario?

**Comment by szaouam** [comment]
@jhunt , yes

**Comment by jhunt** [comment]
Reopening against the SHIELD project proper.
