### ISSUE TITLE
Switch to SQLite for default storage

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/shield-boshrelease#78]
Out-of-the-box, SHIELD should just use a local SQLite3 database - no need for fancy PostgreSQL or MySQL configuration.

**Comment by drnic** [comment]
Is this an important distinction for this boshrelease, which comes with pre-built https://github.com/starkandwayne/shield-boshrelease/blob/master/manifests/shield.yml that describes postgres?

**Comment by jhunt** [comment]
For v8.x single-archive backup it is.

**Comment by jhunt** [comment]
This is done in v8
