### ISSUE TITLE
Number of worker, timeout in the shield-daemon config

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield-boshrelease#88]
Hi,
in the shield-daemon configuration there are two variables that can be configured
- number of workers (default to 5) [link](https://github.com/starkandwayne/shield/blob/master/supervisor/supervisor.go#L27)
- general Timeout for a task (default to 24hours) [link](https://github.com/starkandwayne/shield/blob/master/supervisor/supervisor.go#L37)

The bosh release does not support them, is that on purpose?
Would it be okay for a pull request to add them?

Thanks

**Comment by drnic** [comment]
@karampok sounds good to expose these via job properties
