### ISSUE TITLE
Update `agent-pgtools` to a more recent version or introduce multiple versions

### ISSUE THREAD

**Issue by janaurka** [starkandwayne/shield-boshrelease#89]
Hey

It would be great if the `agent-pgtools` would come with a newer version of `postgres`. Something like `9.6.x` would be fine, since this is latest stable. 

An other option would be to split the package into multiple versions like it’s done for `mongo`.

I’m happy to do so (and also kinda working on it), but it would be cool to agree on how to do it and then do it :)

cheers

**Comment by jhunt** [comment]
The v8 BOSH release (beta candidate coming soon) uses a new set of addon bosh releases that track lots of versions.  See https://github.com/shieldproject?q=addon
