### ISSUE TITLE
SHIELD deployment with mariadb as db

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield-boshrelease#94]
Hi there,
the current bosh release does not include a manifest for testing SHIELD with mariadb.
Testing fast with mariadb in a bosh-lite would great help to find fast potential issues.

Thanks

**Comment by drnic** [comment]
As an fyi, @jhunt said that v8 will have an internal sqlite3 database rather than use pg/mariadb etc

**Comment by jhunt** [comment]
Merged #91, but as @drnic alluded to, the v8 release of SHIELD will move away from standalone relational database stores as part of an effort to streamline backups of SHIELD itself (and its forthcoming encryption capabilities).  The BOSH release will be updated to handle the migration of data transparently.
