### ISSUE TITLE
New Postgres User is not granted access to existing relations in database

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/shield-boshrelease#95]
If the username of the postgres user for the shield database is changed, the shield daemon will fail to start because it won't be able to access any of the existing relations with the new users. We need to add GRANT statements for the relations so that the new user can take over.

**Comment by jhunt** [comment]
This is no longer a concern in v8, which drops support for Postgres outright.

**Comment by thomasmmitchell** [comment]
We may still want to test the path of changing the sqlite user's name, or just revoke the ability to do so entirely.

**Comment by jhunt** [comment]
There's no such thing as a sqlite3 user.  It's just a file, and the BOSH release doesn't allow you to specify the file path.

**Comment by thomasmmitchell** [comment]
bless
